apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/compose/docker-compose.yml convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: passwd-if-redis-server
  name: passwd-if-redis-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: passwd-if-redis-server
    spec:
      containers:
      - args:
        - redis-server
        - --appendonly
        - "yes"
        image: healthcheck/redis
        livenessProbe:
          exec:
            command:
            - docker-healthcheck
          failureThreshold: 3
          periodSeconds: 15
          timeoutSeconds: 30
        name: passwd-if-redis-server
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: redis-volume
      restartPolicy: Always
      volumes:
      - name: redis-volume
        persistentVolumeClaim:
          claimName: redis-volume
status: {}
